### ISSUE TITLE
Zero blur value

### ISSUE THREAD

**Issue by ASchneiderBR** [prgmitchell/blur-filter#1]
Hello! Thank you for sharing this code with us. I am now able to uninstall SFX completely since I only used its blur filter. :)

I was wondering if you could enhance the code by adding a "zero" value option for the blur amount. This would enable me to animate smoothly using Streamer.bot and Exeldro's incredible move filter without any blur. Currently, the lowest value is 1, which still applies some blur to the source, making it difficult to time the animation precisely. It would be great if the filter didn't use any resources and had no blur applied when the value is set to 0, even with the visibility enabled.

Thank you very much!

**Comment by prgmitchell** [comment]
Hello, I will not be making any modifications to the filter.
